language: cpp

notification:
    email:
        on_success: never
        on_failure: never

os: osx

before_install:
    - export HOMEBREW_GITHUB_API_TOKEN=c546650e6386be91992bc502f3ebf662689b91e9
    - brew update
    - brew install llvm37

script:
    - brew list
    - cd /usr/local/Cellar
    - ls
