language: cpp

notification:
    email:
        on_success: never
        on_failure: never

matrix:
    include:
        - os: linux
          compiler: gcc
          env: LINUX_MAIN
          addons:
            apt:
                sources: [ 'ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7' ]
                packages:
                    - gcc-5
                    - clang-3.7
                    - libsqlite3-dev

        - os: linux
          compiler: gcc
          env: LINUX_TEST_CLANG_38
          addons:
            apt:
                sources: [ 'ubuntu-toolchain-r-test', 'llvm-toolchain-precise' ]
                packages:
                    - clang-3.8

        - os: osx
          compiler: clang

    allow_failures:
        env: LINUX_TEST_CLANG_38

addons:
  apt:
    sources: [ 'ubuntu-toolchain-r-test', 'llvm-toolchain-precise' ]
    packages:
        - gcc-5
        - clang-3.8
        - libsqlite3-dev

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        brew update;
        brew install gcc5;
        brew install gcc6;
        brew install llvm38;
        brew install sqlite;
      fi

    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        dpkg -L libsqlite3-dev;
      fi

    - ./download-premake.sh $TRAVIS_OS_NAME

before_script:
    - if [[ $LINUX_MAIN ]]; then
        gcc-5 --version;
        clang-3.7 -- version;
      fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        cat ~/apt-get-update.log;
        cat /etc/apt/sources.list;
        clang-3.8 --version;
      fi

script:
    - ./premake5 --version
    - $CXX --version
