language: cpp
sudo: false
dist: trusty

notification:
    email: false

cache:
    directories:
        - llvm-3.6.2
        - llvm-3.7.1
        - llvm-3.8.0

matrix:
    include:
        - os: linux
          compiler: gcc
          env: LINUX_TEST=main
          addons:
            apt:
                sources: [ 'ubuntu-toolchain-r-test' ]
                packages:
                    - gcc-5
                    - libsqlite3-dev

        - os: linux
          compiler: clang
          env: LLVM_VERSION=3.6.2

        - os: linux
          compiler: clang
          env: LLVM_VERSION=3.7.1

        - os: linux
          compiler: clang
          env: LLVM_VERSION=3.8.0

        - os: osx
          compiler: clang

    allow_failures:
        #- env: LLVM_VERSION=3.6.2
        #- env: LLVM_VERSION=3.7.1
        #- env: LLVM_VERSION=3.8.0

before_install:
    - ./travis-before-install.sh

before_script:
    - ./travis-before-script.sh

script:
    - ./screenfetch.sh
    - ./detect-travis.sh
    - ./premake5 --version
    - $CXX --version
