language: cpp

notification:
    email:
        on_success: never
        on_failure: never

os:
    - linux
    - osx

compiler:
    - clang

addons:
  apt:
    sources: [ 'ubuntu-toolchain-r-test', 'llvm-toolchain-precise' ]
    packages: [ 'clang-3.8', 'libc6-dev=2.17-7' ]

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        brew update;
        brew install llvm37;
      fi

    - ./download-premake.sh $TRAVIS_OS_NAME

before_script:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then CXX=clang++-3.8; fi

script:
    - cd /lib/x86_64-linux-gnu
    - ls -l

    - ./premake5 --version
    - $CXX --version
