language: cpp

notification:
    email:
        on_success: never
        on_failure: never

os: osx

before_install:
    - brew outdated llvm37

script:
    - brew list
    - cd /usr/local/Cellar
    - ls
