language: cpp

notification:
    email:
        on_success: never
        on_failure: never

os:
    - linux
    - osx

addons:
  apt:
    sources: [ 'ubuntu-toolchain-r-test', 'llvm-toolchain-precise' ]
    packages:
        - gcc-5
        - clang-3.8
        - libsqlite3-dev

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        brew update;
        brew install gcc5;
        brew install gcc6;
        brew install llvm38;
        brew install sqlite;
      fi

    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        dpkg -L libsqlite3-dev;
      fi

    - ./download-premake.sh $TRAVIS_OS_NAME

before_script:
    - gcc-5 --version;
    - clang-3.8 --version

script:
    - ./premake5 --version
    - $CXX --version
