language: cpp

notification:
    email:
        on_success: never
        on_failure: never

os:
    - linux
    - osx

compiler:
    - clang

addons:
  apt:
    sources: [ 'ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7' ]
    packages: [ 'clang-3.7' ]

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install llvm37; fi

before_script:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then CXX=clang++-3.7; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd /usr/lib/x86_64-linux-gnu; ls libclang* -l; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ln -s libclang-3.7.so.1 libclang-3.7.so; ls libclang* -l; fi

script:
    - $CXX --version
